### PR TITLE
add StableDeref impls for CString, OsString and PathBuf

### PR DESCRIPTION
**Pull request by sunshowers**
Thanks for doing this crate! I found some of these to be useful while writing code taking advantage of `StableDeref`.

### CODE REVIEW

**Comment by oli-cosmian** [comment]
Could you publish a new version with this change included?

**Comment by Storyyeller** [comment]
I'll do it this weekend.

**Comment by Storyyeller** [comment]
done

**Comment by oli-cosmian** [comment]
Thank you!

**Pull request merged**
